feat: Adding --list-only argument to export a list of active images
lacework-dev/container-auto-scan pull request #1
Opened 2021-12-16 23:28 UTC by mikelaramie

This pull request adds a feature `--list-only` to the auto_scan.py script.  This flag will export a list of active images without triggering a scan.  This is useful for customers who may not have a particular registry integration in Lacework and would like to automate image scans via the inline scanner based on what's currently running in their environment.  

Example output:

```
❯ python auto_scan.py --registry gcr.io --list-only
Fetching container assessments since "2021-12-15T22:46:44Z"...
Previously Assessed Container Count: 10
Building container assessment cache...
Fetching active containers for gcr.io...
Found 11 active containers for gcr.io...
gcr.io/bank-of-anthos/frontend:v0.5.0
gcr.io/bank-of-anthos/contacts:v0.5.0
gcr.io/bank-of-anthos/ledger-db:v0.5.0
gcr.io/bank-of-anthos/loadgenerator:v0.5.0
gcr.io/gke-release/istio/proxyv2:1.6.14-gke.1
gcr.io/bank-of-anthos/accounts-db:v0.5.0
gcr.io/bank-of-anthos/transactionhistory:v0.5.0
gcr.io/bank-of-anthos/balancereader:v0.5.0
gcr.io/gke-release/istio/pilot:1.6.14-gke.1
gcr.io/bank-of-anthos/userservice:v0.5.0
gcr.io/bank-of-anthos/ledgerwriter:v0.5.0
```

2021-12-18 02:25 UTC, alannix-lw requested changes
Thanks for the contribution man!  LGTM pending one nit suggestion, and some simple whitespace removal 👍

2021-12-18 02:25 UTC, alannix-lw commented on auto_scan.py
> +        print(f'{container_registry}/{container_repository}:{container["TAG"]}')
Can this be simplified?

```suggestion

def list_containers(containers):
    for container in containers:
        print(f'{container["REPO"]}:{container["TAG"]}')
```

2021-12-18 02:25 UTC, alannix-lw commented on auto_scan.py
> +                ))
Removing added whitespace.

```suggestion
                initiate_container_scan, lw_client, container_registry, container_repository, container['TAG']
            ))
```

2021-12-18 02:25 UTC, alannix-lw commented on auto_scan.py
> +
```suggestion

```

2021-12-18 02:25 UTC, alannix-lw commented on auto_scan.py
> +
```suggestion

```

2021-12-18 02:25 UTC, alannix-lw commented on auto_scan.py
> +
```suggestion

```

2021-12-18 21:49 UTC, mikelaramie commented on auto_scan.py
> +        print(f'{container_registry}/{container_repository}:{container["TAG"]}')
Good catch! 🤦

2021-12-19 04:10 UTC, alannix-lw approved these changes

2021-12-19 04:11 UTC, merged